"""Create the initial Paperbase schema."""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "20260415_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_authors_normalized_name')
    )
    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_job_type'), 'background_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.create_table('extraction_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope_type', sa.String(length=64), nullable=False),
    sa.Column('schema_payload', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_tags_normalized_name')
    )
    op.create_table('venues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_venues_normalized_name')
    )
    op.create_table('collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('scope_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extraction_profile_id', sa.String(length=36), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_profile_id'], ['extraction_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'title', name='uq_collections_owner_title')
    )
    op.create_table('papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('canonical_title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.String(length=36), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('arxiv_id', sa.String(length=128), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_papers_provider_external')
    )
    op.create_index(op.f('ix_papers_external_id'), 'papers', ['external_id'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=128), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_target_id'), 'annotations', ['target_id'], unique=False)
    op.create_table('collection_papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('membership_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'paper_id', name='uq_collection_papers_collection_paper')
    )
    op.create_index(op.f('ix_collection_papers_collection_id'), 'collection_papers', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_papers_paper_id'), 'collection_papers', ['paper_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_paper_id'), 'datasets', ['paper_id'], unique=False)
    op.create_table('engineering_tricks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineering_tricks_paper_id'), 'engineering_tricks', ['paper_id'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('extraction_profile_id', sa.String(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('diagnostics_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_profile_id'], ['extraction_profiles.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_runs_paper_id'), 'extraction_runs', ['paper_id'], unique=False)
    op.create_table('figures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('figure_label', sa.String(length=128), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('bbox_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_figures_paper_id'), 'figures', ['paper_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('polarity', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_paper_id'), 'findings', ['paper_id'], unique=False)
    op.create_table('glossary_terms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_terms_paper_id'), 'glossary_terms', ['paper_id'], unique=False)
    op.create_table('limitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_limitations_paper_id'), 'limitations', ['paper_id'], unique=False)
    op.create_table('methods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methods_paper_id'), 'methods', ['paper_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_paper_id'), 'metrics', ['paper_id'], unique=False)
    op.create_table('paper_authors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'author_id', name='uq_paper_authors_paper_author')
    )
    op.create_index(op.f('ix_paper_authors_author_id'), 'paper_authors', ['author_id'], unique=False)
    op.create_index(op.f('ix_paper_authors_paper_id'), 'paper_authors', ['paper_id'], unique=False)
    op.create_table('paper_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('file_kind', sa.String(length=64), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('parser_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'storage_uri', name='uq_paper_files_paper_storage')
    )
    op.create_index(op.f('ix_paper_files_paper_id'), 'paper_files', ['paper_id'], unique=False)
    op.create_table('paper_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_record_id', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_record_id', name='uq_paper_sources_provider_record')
    )
    op.create_index(op.f('ix_paper_sources_paper_id'), 'paper_sources', ['paper_id'], unique=False)
    op.create_table('paper_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'tag_id', name='uq_paper_tags_paper_tag')
    )
    op.create_index(op.f('ix_paper_tags_paper_id'), 'paper_tags', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_tags_tag_id'), 'paper_tags', ['tag_id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_paper_id'), 'sections', ['paper_id'], unique=False)
    op.create_table('tables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('table_label', sa.String(length=128), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('bbox_json', sa.JSON(), nullable=False),
    sa.Column('structured_payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tables_paper_id'), 'tables', ['paper_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collection_id', sa.String(length=36), nullable=True),
    sa.Column('saved_query', sa.Text(), nullable=True),
    sa.Column('focus_note', sa.Text(), nullable=True),
    sa.Column('active_filters_json', sa.JSON(), nullable=False),
    sa.Column('pinned_paper_ids_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'title', name='uq_workspaces_owner_title')
    )
    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_status', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_paper_id'), 'chunks', ['paper_id'], unique=False)
    op.create_table('result_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('method_id', sa.String(length=36), nullable=True),
    sa.Column('metric_id', sa.String(length=36), nullable=True),
    sa.Column('split_name', sa.String(length=128), nullable=True),
    sa.Column('value_numeric', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=128), nullable=True),
    sa.Column('comparator_text', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_rows_paper_id'), 'result_rows', ['paper_id'], unique=False)
    op.create_table('evidence_spans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('extraction_run_id', sa.String(length=36), nullable=True),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_id', sa.String(length=36), nullable=True),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('quote_text', sa.Text(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_spans_paper_id'), 'evidence_spans', ['paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_spans_paper_id'), table_name='evidence_spans')
    op.drop_table('evidence_spans')
    op.drop_index(op.f('ix_result_rows_paper_id'), table_name='result_rows')
    op.drop_table('result_rows')
    op.drop_index(op.f('ix_chunks_paper_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_tables_paper_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_sections_paper_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_paper_tags_tag_id'), table_name='paper_tags')
    op.drop_index(op.f('ix_paper_tags_paper_id'), table_name='paper_tags')
    op.drop_table('paper_tags')
    op.drop_index(op.f('ix_paper_sources_paper_id'), table_name='paper_sources')
    op.drop_table('paper_sources')
    op.drop_index(op.f('ix_paper_files_paper_id'), table_name='paper_files')
    op.drop_table('paper_files')
    op.drop_index(op.f('ix_paper_authors_paper_id'), table_name='paper_authors')
    op.drop_index(op.f('ix_paper_authors_author_id'), table_name='paper_authors')
    op.drop_table('paper_authors')
    op.drop_index(op.f('ix_metrics_paper_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_methods_paper_id'), table_name='methods')
    op.drop_table('methods')
    op.drop_index(op.f('ix_limitations_paper_id'), table_name='limitations')
    op.drop_table('limitations')
    op.drop_index(op.f('ix_glossary_terms_paper_id'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    op.drop_index(op.f('ix_findings_paper_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_figures_paper_id'), table_name='figures')
    op.drop_table('figures')
    op.drop_index(op.f('ix_extraction_runs_paper_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_engineering_tricks_paper_id'), table_name='engineering_tricks')
    op.drop_table('engineering_tricks')
    op.drop_index(op.f('ix_datasets_paper_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_collection_papers_paper_id'), table_name='collection_papers')
    op.drop_index(op.f('ix_collection_papers_collection_id'), table_name='collection_papers')
    op.drop_table('collection_papers')
    op.drop_index(op.f('ix_annotations_target_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_papers_external_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_table('collections')
    op.drop_table('venues')
    op.drop_table('tags')
    op.drop_table('extraction_profiles')
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_job_type'), table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_table('authors')
    # ### end Alembic commands ###
